"""initial schema

Revision ID: c77dce9645d7
Revises:
Create Date: 2026-06-16 16:58:41.119395

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types appear in autogenerated migrations)
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c77dce9645d7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("company", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("salary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("easy_apply", sa.Boolean(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("linkedin", "indeed", "glassdoor", "exa", "manual", name="jobsource"),
            nullable=False,
        ),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("dedup_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("embedding_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("posted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_company"), ["company"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_dedup_hash"), ["dedup_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_embedding_id"), ["embedding_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_external_id"), ["external_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_location"), ["location"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_title"), ["title"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_url"), ["url"], unique=False)

    op.create_table(
        "llm_usage",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("operation", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("application_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_usage", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_llm_usage_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_llm_usage_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_usage_model"), ["model"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_usage_operation"), ["operation"], unique=False)

    op.create_table(
        "resumes",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_type", sa.Enum("pdf", "docx", name="resumefiletype"), nullable=False),
        sa.Column("source_filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sections", sa.JSON(), nullable=False),
        sa.Column("embedding_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_base", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("resumes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_resumes_embedding_id"), ["embedding_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_resumes_is_base"), ["is_base"], unique=False)
        batch_op.create_index(batch_op.f("ix_resumes_name"), ["name"], unique=False)

    op.create_table(
        "cover_letters",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("resume_id", sa.Integer(), nullable=True),
        sa.Column(
            "style",
            sa.Enum("concise", "startup", "enterprise", name="coverletterstyle"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pdf_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("docx_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("markdown_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model_used", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cover_letters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cover_letters_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_cover_letters_resume_id"), ["resume_id"], unique=False)

    op.create_table(
        "tailored_resumes",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("base_resume_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("diff", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("score_before", sa.Float(), nullable=True),
        sa.Column("score_after", sa.Float(), nullable=True),
        sa.Column("pdf_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("docx_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("markdown_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("html_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model_used", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_resume_id"],
            ["resumes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tailored_resumes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tailored_resumes_base_resume_id"), ["base_resume_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tailored_resumes_job_id"), ["job_id"], unique=False)

    op.create_table(
        "applications",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("resume_id", sa.Integer(), nullable=True),
        sa.Column("tailored_resume_id", sa.Integer(), nullable=True),
        sa.Column("cover_letter_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "saved",
                "interested",
                "tailored",
                "ready",
                "pending_approval",
                "applied",
                "oa",
                "interview",
                "final_round",
                "offer",
                "rejected",
                name="applicationstatus",
            ),
            nullable=False,
        ),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cover_letter_id"],
            ["cover_letters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tailored_resume_id"],
            ["tailored_resumes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_applications_cover_letter_id"), ["cover_letter_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_applications_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_applications_resume_id"), ["resume_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_applications_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_applications_tailored_resume_id"), ["tailored_resume_id"], unique=False
        )

    op.create_table(
        "ats_scores",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("resume_id", sa.Integer(), nullable=True),
        sa.Column("tailored_resume_id", sa.Integer(), nullable=True),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("keyword_score", sa.Float(), nullable=False),
        sa.Column("skills_score", sa.Float(), nullable=False),
        sa.Column("experience_score", sa.Float(), nullable=False),
        sa.Column("education_score", sa.Float(), nullable=False),
        sa.Column("semantic_score", sa.Float(), nullable=False),
        sa.Column("missing_keywords", sa.JSON(), nullable=False),
        sa.Column("matched_keywords", sa.JSON(), nullable=False),
        sa.Column("strengths", sa.JSON(), nullable=False),
        sa.Column("weaknesses", sa.JSON(), nullable=False),
        sa.Column("suggestions", sa.JSON(), nullable=False),
        sa.Column("model_used", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tailored_resume_id"],
            ["tailored_resumes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ats_scores", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ats_scores_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ats_scores_resume_id"), ["resume_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ats_scores_tailored_resume_id"), ["tailored_resume_id"], unique=False
        )

    op.create_table(
        "approval_workflows",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("ats_score_id", sa.Integer(), nullable=True),
        sa.Column("tailored_resume_id", sa.Integer(), nullable=True),
        sa.Column("cover_letter_id", sa.Integer(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "generated",
                "review_required",
                "approved",
                "applying",
                "applied",
                "rejected",
                name="approvalstate",
            ),
            nullable=False,
        ),
        sa.Column("resume_preview", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cover_letter_preview", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("diff_preview", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reject_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ats_score_id"],
            ["ats_scores.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cover_letter_id"],
            ["cover_letters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tailored_resume_id"],
            ["tailored_resumes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("approval_workflows", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_approval_workflows_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_approval_workflows_state"), ["state"], unique=False)

    op.create_table(
        "automation_runs",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("approval_id", sa.Integer(), nullable=True),
        sa.Column(
            "platform",
            sa.Enum("linkedin", "indeed", "glassdoor", name="automationplatform"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "captcha_detected",
                "timed_out",
                "cancelled",
                "dry_run",
                name="automationstatus",
            ),
            nullable=False,
        ),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("screenshots", sa.JSON(), nullable=False),
        sa.Column("trace_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("log", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approval_workflows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("automation_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_automation_runs_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_automation_runs_approval_id"), ["approval_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_automation_runs_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("automation_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_automation_runs_status"))
        batch_op.drop_index(batch_op.f("ix_automation_runs_approval_id"))
        batch_op.drop_index(batch_op.f("ix_automation_runs_application_id"))

    op.drop_table("automation_runs")
    with op.batch_alter_table("approval_workflows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_workflows_state"))
        batch_op.drop_index(batch_op.f("ix_approval_workflows_application_id"))

    op.drop_table("approval_workflows")
    with op.batch_alter_table("ats_scores", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ats_scores_tailored_resume_id"))
        batch_op.drop_index(batch_op.f("ix_ats_scores_resume_id"))
        batch_op.drop_index(batch_op.f("ix_ats_scores_job_id"))

    op.drop_table("ats_scores")
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_applications_tailored_resume_id"))
        batch_op.drop_index(batch_op.f("ix_applications_status"))
        batch_op.drop_index(batch_op.f("ix_applications_resume_id"))
        batch_op.drop_index(batch_op.f("ix_applications_job_id"))
        batch_op.drop_index(batch_op.f("ix_applications_cover_letter_id"))

    op.drop_table("applications")
    with op.batch_alter_table("tailored_resumes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tailored_resumes_job_id"))
        batch_op.drop_index(batch_op.f("ix_tailored_resumes_base_resume_id"))

    op.drop_table("tailored_resumes")
    with op.batch_alter_table("cover_letters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cover_letters_resume_id"))
        batch_op.drop_index(batch_op.f("ix_cover_letters_job_id"))

    op.drop_table("cover_letters")
    with op.batch_alter_table("resumes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resumes_name"))
        batch_op.drop_index(batch_op.f("ix_resumes_is_base"))
        batch_op.drop_index(batch_op.f("ix_resumes_embedding_id"))

    op.drop_table("resumes")
    with op.batch_alter_table("llm_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_usage_operation"))
        batch_op.drop_index(batch_op.f("ix_llm_usage_model"))
        batch_op.drop_index(batch_op.f("ix_llm_usage_job_id"))
        batch_op.drop_index(batch_op.f("ix_llm_usage_application_id"))

    op.drop_table("llm_usage")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_url"))
        batch_op.drop_index(batch_op.f("ix_jobs_title"))
        batch_op.drop_index(batch_op.f("ix_jobs_source"))
        batch_op.drop_index(batch_op.f("ix_jobs_location"))
        batch_op.drop_index(batch_op.f("ix_jobs_external_id"))
        batch_op.drop_index(batch_op.f("ix_jobs_embedding_id"))
        batch_op.drop_index(batch_op.f("ix_jobs_dedup_hash"))
        batch_op.drop_index(batch_op.f("ix_jobs_company"))

    op.drop_table("jobs")
    # ### end Alembic commands ###
